# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Comics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'

  # Pods for Comics

  target 'ComicsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
